name: my_chat
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0+1
  mobx_codegen: ^2.4.0
  injectable: ^2.3.2
  get_it: ^7.6.4
  provider: ^6.0.5
  auto_route: ^7.8.1
  auto_route_generator: ^7.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  injectable_generator: ^2.4.1
  build_runner: ^2.4.5


flutter:
  uses-material-design: true

