// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwv4QkDOv9SfO6NyhGv4R71h3I3TDjD5Q',
    appId: '1:207845172814:web:06ab42ed109ae9b02cc51f',
    messagingSenderId: '207845172814',
    projectId: 'randlin-chat',
    authDomain: 'randlin-chat.firebaseapp.com',
    storageBucket: 'randlin-chat.appspot.com',
    measurementId: 'G-VF0NJM5THJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWdWgFD5VYKZRahdS9Qy5sV4fefyEBVHI',
    appId: '1:207845172814:android:73a50f1d85ace98a2cc51f',
    messagingSenderId: '207845172814',
    projectId: 'randlin-chat',
    storageBucket: 'randlin-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOGCMDdEjWtmfCfPhL5Mt_iW9Mf52I4Gs',
    appId: '1:207845172814:ios:907ac86000eb15ea2cc51f',
    messagingSenderId: '207845172814',
    projectId: 'randlin-chat',
    storageBucket: 'randlin-chat.appspot.com',
    iosBundleId: 'com.example.myChat',
  );
}
